### ISSUE TITLE
I cannot login. 

### ISSUE THREAD

**Issue by ekinlatu** [keithbox/PPSP-360_Degree_Evaluation_System#3]
HI there,

I'm trying to install the system, but it does not let me in. Im using your provided pass & username (admin, gd00305) both error. I also have inport the sql data to db. no error listed. but cannot login. please help me. 

![image](https://user-images.githubusercontent.com/42025979/43569313-a6eacd98-9669-11e8-8078-f557e91121db.png)

**Comment by keithbox** [comment]
Hi,

Did you update the config files? It seems a connection error between database and php or client to server.
Please provide the connection details under "Network" tab in chrome developer tools.

**Comment by keithbox** [comment]
the login action will make an http request to ConnectionManager.php

1. filter by XHR
2. click on the item to view the connection details
3. capture the response of the connection

it may helps to locate the problem.

**Comment by keithbox** [comment]
please refer to the index.html source, the login request return unsuccess
```
	if(jqXHR_or_errorThrown.status != 200){
          msg = "Unkown Connection Error.";
	}else if(data_or_JqXHR.Status == "LoginFail"){
      var responseText = jqXHR_or_errorThrown.responseText;
		var error = "Username and password incorrect.";
		if(typeof(responseText) == "undefined" && responseText == ""){
          msg = "Server responseText empty.";
		}else{
			msg = error;
		}
	}
```

**Comment by ekinlatu** [comment]
Hi sorry to bother again, but here the screenshot filter by XHR. 
![image](https://user-images.githubusercontent.com/42025979/43753525-d02c1554-9a38-11e8-9f96-e66e367653a8.png)

 It is ok, but why it goes to !=200
![image](https://user-images.githubusercontent.com/42025979/43753550-f04f1ac0-9a38-11e8-85b9-881ed9e7c47f.png)

**Comment by ekinlatu** [comment]
hi, i manage to login now. Just a editing, i change the IP no.  to "localhost" in config.php.

**Comment by Hizbe-Ethiopia** [comment]
Hi, Here I also encountered the same problem as discussed in the above. How can I login this system?
