### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by marsdenmadoka** [keithbox/PPSP-360_Degree_Evaluation_System#4]
Hi Keithbox, i am using your app but it is failing to login returning an unknown connection error

**Comment by keithbox** [comment]
Hi,

Could you check on the connection information in the chrome developer tool and see any error occurred?

**Comment by keithbox** [comment]
If you could not provide further information, I will close this. Please feel free to leave your occurred error information after closed, I will re-open this. Thanks.

**Comment by marsdenmadoka** [comment]
Yaah you can check on the chrome developer tools and find the error..ensure
also you have the required stuffs check the read me file will direct you

On Sep 15, 2019 10:48, "Keith POON" <notifications@github.com> wrote:

Hi,

Could you check on the connection information in the chrome developer tool
and see any error occurred?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keithbox/PPSP-360_Degree_Evaluation_System/issues/4?email_source=notifications&email_token=ALZIAUBQMEXLSENSQDOV6ZDQJXSE5A5CNFSM4IWWUBWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6XLJWA#issuecomment-531543256>,
or mute the thread

**Comment by marsdenmadoka** [comment]
![mike](https://user-images.githubusercontent.com/49446992/66755884-90eb5d00-eea1-11e9-8083-45650f6fd92a.png)

**Comment by marsdenmadoka** [comment]
Sorry sir but it is following a wrong path ie Request URL: http://localhost/web_root/127.0.0.1/model/ConnectionManager.php

**Comment by keithbox** [comment]
always use 127.0.0.1 or your network IP,
could you paste your config.js here?

**Comment by marsdenmadoka** [comment]
Yaah i used the same but still not woirking

**Comment by marsdenmadoka** [comment]
var serverHost = "127.0.0.1";//"http://192.168.0.190/Evaluation";
var webRoot = "127.0.0.1";//"http://192.168.0.190/Evaluation";

var requireLoginPage = "index.html";
var afterLoginPage = "main-menu.html";

var CookiesEffectivePath = '/';

var directiveEditMode = {
	None: 0,
	NUll: 1,
	
	Create: 5,
	Amend: 6,
	Delete: 7,
	View: 8,
	AmendAndDelete: 9,
	ImportExport: 10,
	Import: 11,
	Export: 12,
	
	Copy: 15
}
var reservedPath = {
	controller: 'controller/',
	templateFolder: 'Templates/',
	screenTemplate: 'screen/',
}

**Comment by keithbox** [comment]
Please follow the example pattern,
it should be http://127.0.0.1/web_root/ for your case

**Comment by SanderNunes** [comment]
please help me im facing the same issue

**Comment by dolphinotaku** [comment]
could you try to debug in the chrome developer tool, please check the HTTP request destination
